### ISSUE TITLE
Ingress v1.22+ Issue

### ISSUE THREAD

**Issue by sadikekin** [magnolia-sre/magnolia-docker#8]
Hello there,

I think there is an issue about ingress if you use v1.22+. I fixed it by using the following `ingress.yaml` file.

```yaml
{{- if .Values.ingress.enabled -}}
{{- $fullName := include "magnolia.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "magnolia.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.authorHost }}
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: {{ $fullName }}-author
                port:
                  name: http-author
    - host: {{ .Values.ingress.publicHost }}
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: {{ $fullName }}-public
                port:
                  name: http-public
{{- end }}

```
